### ISSUE TITLE
Intelligent single goal keeping

### ISSUE THREAD

**Issue by Thinge** [romdi/IOS#174]
I feel like single keeping is going to be a pretty important feature in regards to match organisation from now on, so we should make sure it's working as best it can. I think perhaps the empty position should be filled by a bot which can position itself better - so long balls can be picked up/cleared as they normally would be, instead of the keeper getting there too late and an unfair chance being created.

**Comment by Aryan-5711** [comment]
Singlekeeper is a very weird thing. It can be extremely useful in situations that you really can't find a 2nd keeper but singlekeeping is also a dangerous thing. I see it being 'misused' so teams or mixes can start their match quicker than waiting for a 2nd keeper. Some keepers like me and Matt refuse to singlekeeper unless no other option but many others won't have a problem with it. Problem with that is that any potential 2nd keeper that could have played during that stretch of time, can not play anymore because they already started playing with a singlekeeper. You can say that the 2nd keeper can join in during match is live but then that original singlekeeper might be very angry because he was commited to play singlekeeper or/and already enjoyed it before the 2nd keeper hopped in.

There need to be some sort of rule for singlekeeping to what is allowed and what not.
